name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Install PHP dependencies
        working-directory: wordpress-plugin/wordpress-azure-monitor
        run: composer install --no-interaction --prefer-dist

      - name: Run PHPUnit
        working-directory: wordpress-plugin/wordpress-azure-monitor
        run: vendor/bin/phpunit

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build (no push) for test
        uses: docker/bake-action@v5
        with:
          files: |
            ./docker-bake.hcl
          targets: php84
          set: |
            *.platform=linux/amd64
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max

      - name: Load image
        run: |
          docker buildx build --load -f Dockerfile --platform linux/amd64 --build-arg PHP_VERSION=8.4 -t local/wazm:ci .

      - name: Smoke test
        run: |
          bash scripts/smoke-test.sh local/wazm:ci

      - name: Build and push multi-arch
        if: github.ref == 'refs/heads/master'
        uses: docker/bake-action@v5
        with:
          files: |
            ./docker-bake.hcl
          targets: default
          push: true
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max


