name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit on changed files
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            base_ref="origin/${{ github.base_ref }}"
          else
            base_ref="HEAD^"
          fi
          git fetch origin ${{ github.base_ref }} --depth=1 || true
          files=$(git diff --name-only --diff-filter=AMR "$base_ref")
          if [ -n "$files" ]; then
            pre-commit run --files $files
          fi
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build (no push) for test
        uses: docker/bake-action@v5
        with:
          files: |
            ./docker-bake.hcl
          targets: php84
          set: |
            *.platform=linux/amd64
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max

      - name: Load image
        run: |
          docker buildx build --load -f Dockerfile --platform linux/amd64 --build-arg PHP_VERSION=8.4 -t local/wazm:ci .

      - name: Smoke test
        run: |
          bash scripts/smoke-test.sh local/wazm:ci

      - name: Build and push multi-arch
        if: github.ref == 'refs/heads/master'
        uses: docker/bake-action@v5
        with:
          files: |
            ./docker-bake.hcl
          targets: default
          push: true
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max


